### ISSUE TITLE
Question: Dropdown taints

### ISSUE THREAD

**Issue by ckaotik** [Jaliborc/Sushi-3.2#1]
I have just stumbled upon this project of yours and am wondering ... Considering the enormous taint issues involved in Dropdown menus and the likes, did you consider this?
I've just had a peek at the code and it seems you rely on Blizzard's Dropdown menu API calls.

I've been looking for functioning dropdowns for a while and don't really want to rely on LibDropDown's predefined table format, so your framework would be heaven-sent if it does work as intended :)

**Comment by Jaliborc** [comment]
Well, I have never experienced any kind of taint issues with Sushi dropdowns. Now, if you (or anyone else) find any kind of taint, I will workaround the issue.

**Comment by ckaotik** [comment]
The main point I'm wondering about is the topic discussed in the [US Bug forums][http://us.battle.net/wow/en/forum/topic/6413024969]. Apparently when creating dropdowns with 8 ( = Blizzards default max value) or more options, many secure frames created later on get tainted.

In their example it's CompactRaidFrame1, but it can happen with anything using dropdowns (map frame, unit frames, ...). I've often encountered raid frames 1-x (e.g. 3) working fine and suddenly, 4+ are tainted because a dropdown has been initialized in the meantime :(

**Comment by Jaliborc** [comment]
Ok, then I will implement it myself. Fairly busy right now fixing MoP bugs and such but, after that, it will be done.
Should be fairly simple to do thanks to the Sushi power XP. SushiTextureDropdown is also custom code and was quite simple.

**Comment by Jaliborc** [comment]
Oh, this was done a long time ago. Forgot to close.
