### ISSUE TITLE
Shadowlands, 9.0.1 errors:

### ISSUE THREAD

**Issue by yoshimo** [Jaliborc/Sushi-3.2#10]
Date: 2020-08-29 13:23:05
ID: 1
Error occured in: Global
Count: 1
Message: ...PetTracker\libs\Sushi-3.1\classes\drops\Dropdown.lua line 136:
   Invalid data provided for `:SetBackdrop`
Debug:
   [string "=[C]"]: assert()
   [string "@PetTracker\libs\Sushi-3.1\classes\drops\Dropdown.lua"]:136: SetBackdrop()
   [string "@PetTracker\libs\Sushi-3.1\classes\drops\Dropdown.lua"]:48: New()
   [string "@PetTracker\libs\Sushi-3.1\classes\drops\Dropdown.lua"]:57: Toggle()
   [string "@PetTracker\addons\main\features\mapSearch.lua"]:124: ToggleTrackingTypes()
   [string "@PetTracker\addons\main\features\mapSearch.lua"]:71:
      ...AddOns\PetTracker\addons\main\features\mapSearch.lua:71
Locals:
(*temporary) = false
(*temporary) = "Invalid data provided for `:SetBackdrop`"

**Comment by spiralofhope** [comment]
I'll take a look.

**Comment by spiralofhope** [comment]
I don't know how to reproduce this bug.

HOWEVER

When I went looking, it appears that whatever is supplied with PetTracker is a bit dated!

Re-download and refresh all of `PetTracker/libs/Sushi-3.1` from

https://github.com/Jaliborc/Sushi-3.1
