### ISSUE TITLE
Sushi adds ColorPickerFrame.SetupColorPickerAndShow and breaks version checks

### ISSUE THREAD

**Issue by Nevcairiel** [Jaliborc/Sushi-3.2#16]
Sushi adds the ColorPickerFrame.SetupColorPickerAndShow if it does not exist, breaking checks in other addons that might check for that function to be available, and assuming it is the original and works as expected - not some addon replacement function.

It is generally a bad idea to mess with global frames that other addons might use. If you want a handy fallback function, please make it local.

**Comment by Jaliborc** [comment]
Fixed
