### ISSUE TITLE
Leaked global variables

### ISSUE THREAD

**Issue by ckaotik** [Jaliborc/Sushi-3.2#2]
Just stumbled upon these leaked variables: `x`, `y`, `line`, `breakLine`. Putting them in local scope shouldn't break anything :)

``` lua
function Group:Layout ()
    self.limit = self:GetLimit()
    x, y = 0, 0
    line = 0

    function breakLine()
        y = y + line
        line, x = 0, 0
    end
```

**Comment by Jaliborc** [comment]
Oh... my... O.o
Nice catch! Can't believe I forgot to make them local...

Fixed
