### ISSUE TITLE
Messed up backdrop texture & Missing CloseDropDownMenus issue

### ISSUE THREAD

**Issue by AndreWaehlisch** [Jaliborc/Sushi-3.2#4]
I am trying to use the dropdown class and I am having some issues. I am using the [example code](https://github.com/Jaliborc/Sushi-3.0/wiki/Dropdown) from the wiki page.

1.: After selecting an item I need _two_ clicks on the arrow button to show the dropdown menu again. Adding the following line after line 104 in DropdownFrame.lua fixes this for me (this is the line with self:SetShown(data.keepShownOnClick)). Don't know if it is the correct position though: `if not data.keepShownOnClick then CloseDropDownMenus() end`

2.: After selecting an item and then clicking the arrow button again (twice, with the above issue) to show the menu will display the dropdown menu, but the backdrop texture will be all messed up (see the attached image). Just clicking the arrow button (without selecting any items) will display it just fine.
![image](https://cloud.githubusercontent.com/assets/7422075/25103142/acd0ccb6-23bb-11e7-9a6a-9bce590662d8.png)

**Comment by Jaliborc** [comment]
I have no idea what is causing this. Never seen it nor can reproduce.

**Comment by AndreWaehlisch** [comment]
Testing again on the now current retail version: While the first problem still exists, the second seems to be fixed for me (maybe it was a bug on Blizzards side).
