### ISSUE TITLE
Wiki missing?

### ISSUE THREAD

**Issue by Mindustry** [Jaliborc/Sushi-3.2#7]
Am I blind or has the wiki that is linked to several times on the README gone completely missing?

**Comment by Jaliborc** [comment]
I'm about to release 3.1, a massive rewrite, which will make the wiki very outdated and misleading.
Not sure if I should keep it on or disable it.

**Comment by Mindustry** [comment]
Ah, understood. I excitedly await the release then.

**Comment by Jaliborc** [comment]
Its already available on the experimental branch. Currently testing on a beta period using Bagnon on which I can still change the API.
